### ISSUE TITLE
Failed to export app icon

### ISSUE THREAD

**Issue by pratamawijaya** [Ashung/android-res-export-figma#1]
Hi, thanks for the plugin, 

I have some problem when trying to export app icon, I have selected my layer n then open menu plugins, then export app icon, but somehow it doesn't show my icon, just a guide red line,

![image](https://user-images.githubusercontent.com/2455823/62436170-02ec4b00-b769-11e9-80d7-f44438af028d.png)

**Comment by Ashung** [comment]
Make sure you have only 1 page call "app icon" in you document.

**Comment by pratamawijaya** [comment]
@Ashung oke thanks
