### ISSUE TITLE
Nothing happen when click save button

### ISSUE THREAD

**Issue by longnguyen0410** [Ashung/android-res-export-figma#10]
Yesterday, it worked fine. But today, it does not work. is it a bug on new update?

**Comment by dhairyagandhi** [comment]
Happening for me too, seems like the new update has this issue.

**Comment by behbudovusal** [comment]
Happening for me too

**Comment by jeremycochoy** [comment]
Some problem, it looks like the last update broke the plugin :(

**Comment by jeremycochoy** [comment]
Looking at the error, we got
```
VM381:8 Uncaught (in promise) Error: Invalid base64 input, bad content length.
    at Object.e.decode (<anonymous>:8:208291)
    at <anonymous>:1:5015`.
```

Edit: I managed to compile localy the master branch, and everything works fine on my computer. I do not know where the error of the release version comes from. :/

Doc on building: https://www.figma.com/plugin-docs/bundling-webpack/

**Comment by hyllus** [comment]
Same issue here.  I guess I'll build it locally as well.

**Comment by rezpilehvar** [comment]
same issue

**Comment by apurvasaxena** [comment]
same issue. "Export" button does nothing

**Comment by behbudovusal** [comment]
@Ashung ?

**Comment by Ashung** [comment]
Fixed.
