### ISSUE TITLE
Export adaptive icon as vector drawable

### ISSUE THREAD

**Issue by nirav-tukadiya** [Ashung/android-res-export-figma#3]
Currently, it only exports foreground and background images in png. It does not export vector images that can be used in Android 8 and above. 
See the guidelines below:
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by Ashung** [comment]
Use this plugin https://www.figma.com/c/plugin/797369763563831541/Android-Vector-Drawable
