### ISSUE TITLE
Faulty 9-patch export 

### ISSUE THREAD

**Issue by nathanvogel** [Ashung/android-res-export-figma#8]
Hi, 

The 9 patch export doesn't quite work for me, see with this example file: 
https://www.figma.com/file/LAOyXyAxSep6T0nzo0HN41/AndroidResExport-plugin-issue-demo?node-id=1%3A2

MDPI: bars aren't 100% black and are "blurred" on the width.
![button_fx_background_pressed 9](https://user-images.githubusercontent.com/3106715/78082501-79eae980-73b3-11ea-8a92-8e641074399e.png)

HDPI: Bottom and right bars aren't visible
![button_fx_background_pressed 9](https://user-images.githubusercontent.com/3106715/78082507-7e170700-73b3-11ea-91cf-1a6da81444bd.png)

I've tested with multiple resolution (52x52, 50x50, 36x36 and 38x38) and variations of this issue arise. 

Thank you for the free and open-source plugin anyway!

**Comment by Ashung** [comment]
I fixed the 9-patch hdpi bug, you can't scale the layer, patch lines must be 1px width.
